---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
env:
  global:
    - SHELLCHECK_OPTS="-e SC1117"
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.1
      script:
      - bundle exec rake 'litmus:provision_list[travis_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=deb_puppet6
      rvm: 2.5.1
      script:
      - time bundle exec rake 'litmus:provision_list[travis_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - time bundle exec rake 'litmus:install_agent[puppet6]'
      - time bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el_puppet5
      rvm: 2.5.1
      script:
      - bundle exec rake 'litmus:provision_list[travis_el]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el_puppet6
      rvm: 2.5.1
      script:
      - bundle exec rake 'litmus:provision_list[travis_el]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
    -
      env: CHECK="shellcheck tasknames"
      stage: static
branches:
  only:
    - master
    - /^v\d/
    - /.*/
notifications:
  email: false
